services:
  servicio-turnos:
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    volumes:
      - .:/app

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
